apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minetrack
resources:
  - minetrack-namespace.yaml
  - minetrack-configmap.yaml
  - minetrack-deployment.yaml
  - minetrack-service.yaml